services:

  shard2s1:
    container_name: configs_shard2s1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20011:27017
    volumes:
      - shard2s1:/data/db

  shard2s2:
    container_name: configs_shard2s2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20012:27017
    volumes:
      - shard2s2:/data/db

  shard2s3:
    container_name: configs_shard2s3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20013:27017
    volumes:
      - shard2s3:/data/db

volumes:
  shard2s1: {}
  shard2s2: {}
  shard2s3: {}